### PR TITLE
Apply requirements test

### PR DESCRIPTION
**Pull request by lilincmu**

### CODE REVIEW

**Comment by lilincmu** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # null_resource.example6 will be created
+ resource "null_resource" "example6" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://li-VW9LJD927F:4141/lock?id=hashicorp%252Fatlantis-repo-lilin%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by tf-vcs-testing** [comment]
atlantis apply

**Comment by lilincmu** [comment]
Ran Apply for dir: `.` workspace: `default`

**Apply Failed**: Pull request must be mergeable before running apply.

**Review by hc-github-team-tf-commercial — APPROVED** [review]

**Comment by lilincmu** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
